### ISSUE TITLE
Replace IP addresses for hostnames

### ISSUE THREAD

**Issue by atcasanova** [shizunge/blocky-postgresql#3]
Hey, I use a DHCP system where I associate each client's MAC address to one specifc IP. 
So i would like to change the dashboard to replace the IP Addresses with their respective hostnames. Is it possible? Would you give me an overview on how to do that?

I don't want it do make a reverse name resolving or anything like that. I just want to replace the strings.

Thanks in advance

**Comment by shizunge** [comment]
Usually the client name to client ip is a multiple to one map, that is why I hidden it.
I would say that the best way is to assign each client a human readable name. I think you can do it in blocky via [Custom client name mapping](https://0xerr0r.github.io/blocky/v0.21/configuration/#custom-client-name-mapping)

You can show the client ip in top clients tables (firstly make the dashboard editable):
<img width="424" alt="Screenshot 2023-06-10 112222" src="https://github.com/shizunge/blocky-postgresql-dashboard/assets/1281491/2a8fb60f-5cf4-4bd9-958b-1b10199d2958">

<img width="536" alt="Screenshot 2023-06-10 112647" src="https://github.com/shizunge/blocky-postgresql-dashboard/assets/1281491/feb9ed8d-dbf9-46e0-821a-38ae4fb14898">

It needs more work to filter by client ip. As I suggested, try  [Custom client name mapping](https://0xerr0r.github.io/blocky/v0.21/configuration/#custom-client-name-mapping) first to see if it solves your problem.

Edit:
It seems [Custom client name mapping](https://0xerr0r.github.io/blocky/v0.21/configuration/#custom-client-name-mapping) rather than [Custom DNS](https://0xerr0r.github.io/blocky/v0.21/configuration/#custom-dns)

**Comment by atcasanova** [comment]
Actually i added all the mappings to the clientLookup section in my config.yml for blocky and it seems to work!

Thanks a lot!
